application: progetto-abaco
version: 1b
runtime: python27
api_version: 1
threadsafe: true

handlers:

- url: /statici/caratteri
  static_dir: statici/caratteri
  mime_type: application/octet-stream

- url: /liste
  static_dir: liste
  application_readable: true

- url: /statici
  static_dir: statici

- url: /.*
  script: progetto-abaco.app

libraries:
- name: jinja2
  version: latest
